#!/bin/bash
set -e
set -u

data=/var/www/html/data
PGHOST=${PGHOST:-postgres}
PGPORT=${PGPORT:-5432}
PGDATABASE=${PGDATABASE:-postgres}
PGUSER=${PGUSER:-postgres}
PGPASSWORD=${PGPASSWORD:-postgres}

if rpm --quiet -q httpd24-httpd ; then
  x=/opt/rh/httpd24/root
  runner=( scl enable httpd24 -- )
else
  x=''
  runner=()
fi
conf_d=${x}/etc/httpd/conf.d
test_conf=${conf_d}/test.conf
httpd=${x}/usr/sbin/httpd

cat >> "$test_conf" <<EOF
#DBDriver pgsql
#DBDParams postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
# TODO: convert these from proftpd
#SQLNamedQuery	get-user-by-name SELECT "name, pass, uid+100000, uid+100000, '/ftp', '/usr/sbin/nologin' FROM users_field_data WHERE name = '%U' AND status = 1"
#SQLNamedQuery	get-user-by-id SELECT "name, pass, uid+100000, uid+100000, '/ftp', '/usr/sbin/nologin' FROM users_field_data WHERE uid+100000 = %{0} AND status = 1"
#SQLNamedQuery	get-user-names SELECT "name FROM users_field_data WHERE status = 1"
#SQLNamedQuery	get-all-users SELECT "name, pass, uid+100000, uid+100000, '/ftp', '/usr/sbin/nologin' FROM users_field_data WHERE status = 1"
#SQLNamedQuery	get-group-by-name SELECT "ur.roles_target_id, ('x'||substring(md5(ur.roles_target_id) from 7 for 4))::bit(16)::int+200000, ufd.name FROM user__roles ur INNER JOIN users_field_data ufd ON ur.entity_id = ufd.uid WHERE ur.roles_target_id = '%{0}' AND ufd.status = 1"
#SQLNamedQuery	get-group-by-id SELECT "ur.roles_target_id, ('x'||substring(md5(ur.roles_target_id) from 7 for 4))::bit(16)::int+200000, ufd.name FROM user__roles ur INNER JOIN users_field_data ufd ON ur.entity_id = ufd.uid WHERE ('x'||substring(md5(ur.roles_target_id) from 7 for 4))::bit(16)::int+200000 = %{0} AND ufd.status = 1"
#SQLNamedQuery	get-group-by-member SELECT "ur.roles_target_id, ('x'||substring(md5(ur.roles_target_id) from 7 for 4))::bit(16)::int+200000, ufd.name FROM user__roles ur INNER JOIN users_field_data ufd ON ur.entity_id = ufd.uid WHERE ufd.name = '%{0}' AND ufd.status = 1"
#SQLNamedQuery	get-all-groupnames SELECT "DISTINCT roles_target_id FROM user__roles"
#SQLNamedQuery	get-all-groups SELECT "ur.roles_target_id, ('x'||substring(md5(ur.roles_target_id) from 7 for 4))::bit(16)::int+200000, ufd.name FROM user__roles ur INNER JOIN users_field_data ufd ON ur.entity_id = ufd.uid WHERE ufd.status = 1"
EOF

for id in 0 1 2 ; do
  case "$id" in
  0)
    team=everyone
    teamfolder=${data}
    teamrequire="all granted"
    ;;
  *)
    team=team${id}
    teamfolder=${data}/${team}
    teamrequire="group $team"
    ;;
  esac

  mkdir -p -- "$teamfolder"
  echo "$team can read this" > "$teamfolder"/readme.txt

  cat >> "$test_conf" <<EOF

<Directory "$teamfolder">
    Require $teamrequire
</Directory>
EOF
done
"${runner[@]}" $httpd -t

exec $httpd -DFOREGROUND
