#!/bin/bash
set -e
set -u

data=/data

mkdir -p "$data"

for id in 0 1 2 ; do
  case "$id" in
  0)
    team=everyone
    teamfolder=${data}
    teamrequire="all granted"
    user=''
    ;;
  *)
    team=team${id}
    teamfolder=${data}/${team}
    teamrequire="dbd-group $team"
    user=user${team#team}
    ;;
  esac

  mkdir -p -- "$teamfolder"
  echo "$team can read this" > "$teamfolder"/readme.txt
  echo "Require $teamrequire" > "$teamfolder"/.htaccess
done
