#!/bin/bash
set -e
set -u

pfconf=/etc/proftpd.conf

getpfconf () {
  local name=$1
  sed -n -r -e "s/^$name\s+\"?(.*)\"?\s*\$/\1/p" -- "$pfconf"
}

data=$(getpfconf DefaultRoot)

PGHOST=${PGHOST:-postgres}
PGPORT=${PGPORT:-5432}
PGDATABASE=${PGDATABASE:-postgres}
PGUSER=${PGUSER:-postgres}
PGPASSWORD=${PGPASSWORD:-postgres}

prev=$(cat "$pfconf")
cat >> "$pfconf" <<EOF
SQLConnectInfo  ${PGDATABASE}@${PGHOST}:${PGPORT} ${PGUSER} ${PGPASSWORD}
EOF

for id in 0 1 2 ; do
  case "$id" in
  0)
    team=everyone
    teamfolder=${data}
    teamfolderchroot=${teamfolder}
    teamallow="AllowAll"
    ;;
  *)
    team=team${id}
    teamfolder=${data}/${team}
    teamfolderchroot=${teamfolder}
    teamallow="AllowGroup $team"
    ;;
  esac

  mkdir -p -- "$teamfolder"
  echo "$team can read this" > "$teamfolder"/readme.txt

  cat >> "$pfconf" <<EOF

<Directory "$teamfolderchroot">
  <Limit CWD PWD DIRS READ>
    $teamallow
  </Limit>
  <Limit ALL>
    DenyAll
  </Limit>
</Directory>
EOF
done
if ! proftpd -t ; then
  rv=$?
  diff -u - <<<"$prev" "$pfconf" || :
  exit $rv
fi

exec /usr/sbin/proftpd --nodaemon
