#!/bin/bash
set -e
set -u

pfconf=/etc/proftpd.conf
uidbase=100000
gidbase=200000

getpfconf () {
  local name=$1
  sed -n -r -e "s/^$name\s+\"?(.*)\"?\s*\$/\1/p" -- "$pfconf"
}

pfusers=$(getpfconf AuthUserFile)
pfgroups=$(getpfconf AuthGroupFile)
data=$(getpfconf DefaultRoot)

prev=$(cat "$pfconf")
for id in 0 1 2 ; do
  case "$id" in
  0)
    team=everyone
    teamfolder=${data}
    teamfolderchroot=${teamfolder}
    teamallow="AllowAll"
    teamdefchdir=''
    ;;
  *)
    user=user${id}
    team=team${id}
    teamfolder=${data}/${team}
    teamfolderchroot=${teamfolder}
    teamallow="AllowGroup $team"
    teamdefchdir="DefaultChdir $team $team"
    let uid="$uidbase + $id"
    let gid="$gidbase + $id"
    gecos="User $id"

    opts=(
        --passwd
        --file="$pfusers"
        --name="$user"
        --uid="$uid"
        --gid="$uid"
        --home="$data"
        --shell=/usr/sbin/nologin
        --stdin
    )
    ftpasswd "${opts[@]}" <<<"$user"
    opts=(
        --group
        --file="$pfgroups"
        --name="$team"
        --gid="$gid"
        --member="$user"
    )
    ftpasswd "${opts[@]}"
    ;;
  esac

  mkdir -p -- "$teamfolder"
  echo "$team can read this" > "$teamfolder"/readme.txt

  cat >> "$pfconf" <<EOF

<Directory "$teamfolderchroot">
  <Limit CWD PWD DIRS READ>
    $teamallow
  </Limit>
  <Limit ALL>
    DenyAll
  </Limit>
</Directory>
EOF
done
if ! proftpd -t ; then
  rv=$?
  diff -u - <<<"$prev" "$pfconf" || :
  exit $rv
fi

exec /usr/sbin/proftpd --nodaemon
